[tool.ruff]
line-length = 120
include = ["pyproject.toml", "nbody/**/*.py", "*.py"]

[tool.ruff.lint]
select = ["A", "E", "F", "N", "COM", "SIM"]
ignore = [
  "E711", # COMPARISON TO FALSE
  "E712", # COMPARISON TO TRUE 
  "N807"
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"] # ignore module imports
"**/tests/*" = ["E402"]
