
name: Python CI - pytest
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'nbody/**.py'
      - '*.py'
  workflow_dispatch: 
jobs:
  build-tests:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        module-name: ['base', 'core', 'tools']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        pip install -r requirements.txt
    - with:
        test-file: ${{ matr.module-name }}
    - name: Pytest -> ${{ test-file }}
      run: |
        pytest -v --disable-warnings -l **/tests/test_${{ test-file }}.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}  
  
  
  
  
  
  build-linter:
    name: Pylint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8","3.9", "3.12"]
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            cache: pip
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ruff
            pip install -r requirements.txt
        - name: Analysing the code with pylint
          run: |
            pip install ruff
            ruff --output-format=github .
            continue-on-error: true
            

