
name: 'pytest'
on:
  workflow_run:
    workflows: CI (Ingest) - Ruff
  workflow_dispatch:
  
jobs:
  build-tests:
    name: Pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        pip install -r requirements.txt
    - name: Pytest run
      run: |
        pytest -v --disable-warnings -l **/tests/test*.py --doctest-modules --junitxml=junit/test-results.xml --cov=nbody --cov-report=xml --cov-report=html
    - name: Upload pytest results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-${{ matrix.python-version }}-base
        path: junit/test-results-${{ matrix.python-version }}-base.xml
      if: ${{ always() }}  
  
 

            

