
name: Python CI - pytest
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'nbody/**.py'
      - '*.py'
  workflow_dispatch: 
jobs:
  
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        module-name: ['base', 'core', 'tools']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
    - name: Pytest -> ${{ matrix.module-name }}$
      run: |
        pytest -v --disable-warnings -l **/tests/test_${{ matrix.module-name }}.py
